// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/statnusa/DenseTerminal.tsx": () => import("../components/mockups/statnusa/DenseTerminal.tsx"),
  "./components/mockups/statnusa/MinimalMono.tsx": () => import("../components/mockups/statnusa/MinimalMono.tsx"),
  "./components/mockups/statnusa/SoftOfficial.tsx": () => import("../components/mockups/statnusa/SoftOfficial.tsx"),
  "./components/mockups/statnusa/WarmEditorial.tsx": () => import("../components/mockups/statnusa/WarmEditorial.tsx")
};
